/*
** EPITECH PROJECT, 2022
** strace
** File description:
** Declares entries
*/

#pragma once

#include "../../strace.h"
#include "print_raw_arguments.h"
#include <sys/syscall.h>
#include <stddef.h>

int strace_syscall_print_sys_execve(struct strace *self,
    struct strace_process *proc);
int strace_syscall_print_sys_execveat(struct strace *self,
    struct strace_process *proc);

static const struct strace_syscall_entry STRACE_SYSCALL_ENTRIES[] = {
    [SYS_execve] = {
        .function = &strace_syscall_print_sys_execve,
        .number = SYS_execve,
        .name = "execve",
        .num_arguments = 3,
    },
    [SYS_execveat] = {
        .function = &strace_syscall_print_sys_execveat,
        .number = SYS_execveat,
        .name = "execveat",
        .num_arguments = 5,
    },
    [SYS_exit] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_exit,
        .name = "exit",
        .num_arguments = 1,
    },
    [SYS_exit_group] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_exit,
        .name = "exit_group",
        .num_arguments = 1,
    },
    [SYS_brk] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_brk,
        .name = "brk",
        .num_arguments = 1,
    },
    [SYS_arch_prctl] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_arch_prctl,
        .name = "arch_prctl",
        .num_arguments = 2,
    },
    [SYS_access] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_access,
        .name = "access",
        .num_arguments = 2,
    },
    [SYS_openat] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_openat,
        .name = "openat",
        .num_arguments = 4,
    },
    [SYS_newfstatat] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_newfstatat,
        .name = "newfstatat",
        .num_arguments = 4,
    },
    [SYS_mmap] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_mmap,
        .name = "mmap",
        .num_arguments = 6,
    },
    [SYS_close] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_close,
        .name = "close",
        .num_arguments = 1,
    },
    [SYS_read] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_read,
        .name = "read",
        .num_arguments = 3,
    },
    [SYS_pread64] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_pread64,
        .name = "pread64",
        .num_arguments = 4,
    },
    [SYS_mprotect] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_mprotect,
        .name = "mprotect",
        .num_arguments = 3,
    },
    [SYS_set_tid_address] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_set_tid_address,
        .name = "set_tid_address",
        .num_arguments = 1,
    },
    [SYS_set_robust_list] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_set_robust_list,
        .name = "set_robust_list",
        .num_arguments = 2,
    },
    [SYS_prlimit64] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_prlimit64,
        .name = "prlimit64",
        .num_arguments = 4,
    },
    [SYS_munmap] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_munmap,
        .name = "munmap",
        .num_arguments = 2,
    },
    [SYS_getrandom] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getrandom,
        .name = "getrandom",
        .num_arguments = 3,
    },
    [SYS_futex] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_futex,
        .name = "futex",
        .num_arguments = 6,
    },
    [SYS_write] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_write,
        .name = "write",
        .num_arguments = 3,
    },
    [SYS_ioctl] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_ioctl,
        .name = "ioctl",
        .num_arguments = 3,
    },
    [SYS_statfs] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_statfs,
        .name = "statfs",
        .num_arguments = 2,
    },
    [SYS_open] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_open,
        .name = "open",
        .num_arguments = 2,
    },
    [SYS_stat] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_stat,
        .name = "stat",
        .num_arguments = 2,
    },
    [SYS_fstat] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_fstat,
        .name = "fstat",
        .num_arguments = 2,
    },
    [SYS_lstat] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_lstat,
        .name = "lstat",
        .num_arguments = 2,
    },
    [SYS_poll] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_poll,
        .name = "poll",
        .num_arguments = 3,
    },
    [SYS_lseek] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_lseek,
        .name = "lseek",
        .num_arguments = 3,
    },
    [SYS_rt_sigaction] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_rt_sigaction,
        .name = "rt_sigaction",
        .num_arguments = 6,
    },
    [SYS_rt_sigprocmask] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_rt_sigprocmask,
        .name = "rt_sigprocmask",
        .num_arguments = 4,
    },
    [SYS_rt_sigreturn] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_rt_sigreturn,
        .name = "rt_sigreturn",
        .num_arguments = 6,
    },
    [SYS_pwrite64] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_pwrite64,
        .name = "pwrite64",
        .num_arguments = 6,
    },
    [SYS_readv] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_readv,
        .name = "readv",
        .num_arguments = 3,
    },
    [SYS_writev] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_writev,
        .name = "writev",
        .num_arguments = 3,
    },
    [SYS_pipe] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_pipe,
        .name = "pipe",
        .num_arguments = 1,
    },
    [SYS_select] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_select,
        .name = "select",
        .num_arguments = 5,
    },
    [SYS_sched_yield] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_sched_yield,
        .name = "sched_yield",
        .num_arguments = 1,
    },
    [SYS_mremap] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_mremap,
        .name = "mremap",
        .num_arguments = 0,
    },
    [SYS_msync] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_msync,
        .name = "msync",
        .num_arguments = 3,
    },
    [SYS_mincore] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_mincore,
        .name = "mincore",
        .num_arguments = 3,
    },
    [SYS_madvise] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_madvise,
        .name = "madvise",
        .num_arguments = 3,
    },
    [SYS_shmget] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_shmget,
        .name = "shmget",
        .num_arguments = 3,
    },
    [SYS_shmat] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_shmat,
        .name = "shmat",
        .num_arguments = 3,
    },
    [SYS_shmctl] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_shmctl,
        .name = "shmctl",
        .num_arguments = 3,
    },
    [SYS_dup] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_dup,
        .name = "dup",
        .num_arguments = 1,
    },
    [SYS_dup2] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_dup2,
        .name = "dup2",
        .num_arguments = 2,
    },
    [SYS_pause] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_pause,
        .name = "pause",
        .num_arguments = 1,
    },
    [SYS_nanosleep] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_nanosleep,
        .name = "nanosleep",
        .num_arguments = 2,
    },
    [SYS_getitimer] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getitimer,
        .name = "getitimer",
        .num_arguments = 2,
    },
    [SYS_alarm] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_alarm,
        .name = "alarm",
        .num_arguments = 1,
    },
    [SYS_setitimer] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_setitimer,
        .name = "setitimer",
        .num_arguments = 3,
    },
    [SYS_getpid] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getpid,
        .name = "getpid",
        .num_arguments = 1,
    },
    [SYS_sendfile] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_sendfile,
        .name = "sendfile",
        .num_arguments = 4,
    },
    [SYS_socket] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_socket,
        .name = "socket",
        .num_arguments = 3,
    },
    [SYS_connect] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_connect,
        .name = "connect",
        .num_arguments = 3,
    },
    [SYS_accept] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_accept,
        .name = "accept",
        .num_arguments = 3,
    },
    [SYS_sendto] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_sendto,
        .name = "sendto",
        .num_arguments = 6,
    },
    [SYS_recvfrom] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_recvfrom,
        .name = "recvfrom",
        .num_arguments = 6,
    },
    [SYS_sendmsg] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_sendmsg,
        .name = "sendmsg",
        .num_arguments = 3,
    },
    [SYS_recvmsg] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_recvmsg,
        .name = "recvmsg",
        .num_arguments = 3,
    },
    [SYS_shutdown] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_shutdown,
        .name = "shutdown",
        .num_arguments = 2,
    },
    [SYS_bind] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_bind,
        .name = "bind",
        .num_arguments = 3,
    },
    [SYS_listen] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_listen,
        .name = "listen",
        .num_arguments = 2,
    },
    [SYS_getsockname] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getsockname,
        .name = "getsockname",
        .num_arguments = 3,
    },
    [SYS_getpeername] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getpeername,
        .name = "getpeername",
        .num_arguments = 3,
    },
    [SYS_socketpair] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_socketpair,
        .name = "socketpair",
        .num_arguments = 4,
    },
    [SYS_setsockopt] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_setsockopt,
        .name = "setsockopt",
        .num_arguments = 5,
    },
    [SYS_getsockopt] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getsockopt,
        .name = "getsockopt",
        .num_arguments = 5,
    },
    [SYS_clone] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_clone,
        .name = "clone",
        .num_arguments = 0,
    },
    [SYS_fork] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_fork,
        .name = "fork",
        .num_arguments = 1,
    },
    [SYS_vfork] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_vfork,
        .name = "vfork",
        .num_arguments = 1,
    },
    [SYS_wait4] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_wait4,
        .name = "wait4",
        .num_arguments = 4,
    },
    [SYS_kill] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_kill,
        .name = "kill",
        .num_arguments = 2,
    },
    [SYS_uname] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_uname,
        .name = "uname",
        .num_arguments = 1,
    },
    [SYS_semget] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_semget,
        .name = "semget",
        .num_arguments = 3,
    },
    [SYS_semop] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_semop,
        .name = "semop",
        .num_arguments = 3,
    },
    [SYS_semctl] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_semctl,
        .name = "semctl",
        .num_arguments = 4,
    },
    [SYS_shmdt] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_shmdt,
        .name = "shmdt",
        .num_arguments = 1,
    },
    [SYS_msgget] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_msgget,
        .name = "msgget",
        .num_arguments = 2,
    },
    [SYS_msgsnd] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_msgsnd,
        .name = "msgsnd",
        .num_arguments = 4,
    },
    [SYS_msgrcv] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_msgrcv,
        .name = "msgrcv",
        .num_arguments = 5,
    },
    [SYS_msgctl] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_msgctl,
        .name = "msgctl",
        .num_arguments = 3,
    },
    [SYS_fcntl] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_fcntl,
        .name = "fcntl",
        .num_arguments = 0,
    },
    [SYS_flock] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_flock,
        .name = "flock",
        .num_arguments = 2,
    },
    [SYS_fsync] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_fsync,
        .name = "fsync",
        .num_arguments = 1,
    },
    [SYS_fdatasync] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_fdatasync,
        .name = "fdatasync",
        .num_arguments = 1,
    },
    [SYS_truncate] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_truncate,
        .name = "truncate",
        .num_arguments = 2,
    },
    [SYS_ftruncate] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_ftruncate,
        .name = "ftruncate",
        .num_arguments = 2,
    },
    [SYS_getdents] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getdents,
        .name = "getdents",
        .num_arguments = 3,
    },
    [SYS_getcwd] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getcwd,
        .name = "getcwd",
        .num_arguments = 2,
    },
    [SYS_chdir] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_chdir,
        .name = "chdir",
        .num_arguments = 1,
    },
    [SYS_fchdir] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_fchdir,
        .name = "fchdir",
        .num_arguments = 1,
    },
    [SYS_rename] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_rename,
        .name = "rename",
        .num_arguments = 2,
    },
    [SYS_mkdir] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_mkdir,
        .name = "mkdir",
        .num_arguments = 2,
    },
    [SYS_rmdir] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_rmdir,
        .name = "rmdir",
        .num_arguments = 1,
    },
    [SYS_creat] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_creat,
        .name = "creat",
        .num_arguments = 2,
    },
    [SYS_link] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_link,
        .name = "link",
        .num_arguments = 2,
    },
    [SYS_unlink] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_unlink,
        .name = "unlink",
        .num_arguments = 1,
    },
    [SYS_symlink] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_symlink,
        .name = "symlink",
        .num_arguments = 2,
    },
    [SYS_readlink] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_readlink,
        .name = "readlink",
        .num_arguments = 3,
    },
    [SYS_chmod] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_chmod,
        .name = "chmod",
        .num_arguments = 2,
    },
    [SYS_fchmod] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_fchmod,
        .name = "fchmod",
        .num_arguments = 2,
    },
    [SYS_chown] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_chown,
        .name = "chown",
        .num_arguments = 3,
    },
    [SYS_fchown] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_fchown,
        .name = "fchown",
        .num_arguments = 3,
    },
    [SYS_lchown] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_lchown,
        .name = "lchown",
        .num_arguments = 3,
    },
    [SYS_umask] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_umask,
        .name = "umask",
        .num_arguments = 1,
    },
    [SYS_gettimeofday] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_gettimeofday,
        .name = "gettimeofday",
        .num_arguments = 2,
    },
    [SYS_getrlimit] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getrlimit,
        .name = "getrlimit",
        .num_arguments = 2,
    },
    [SYS_getrusage] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getrusage,
        .name = "getrusage",
        .num_arguments = 2,
    },
    [SYS_sysinfo] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_sysinfo,
        .name = "sysinfo",
        .num_arguments = 1,
    },
    [SYS_times] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_times,
        .name = "times",
        .num_arguments = 1,
    },
    [SYS_ptrace] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_ptrace,
        .name = "ptrace",
        .num_arguments = 4,
    },
    [SYS_getuid] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getuid,
        .name = "getuid",
        .num_arguments = 1,
    },
    [SYS_syslog] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_syslog,
        .name = "syslog",
        .num_arguments = 3,
    },
    [SYS_getgid] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getgid,
        .name = "getgid",
        .num_arguments = 1,
    },
    [SYS_setuid] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_setuid,
        .name = "setuid",
        .num_arguments = 1,
    },
    [SYS_setgid] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_setgid,
        .name = "setgid",
        .num_arguments = 1,
    },
    [SYS_geteuid] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_geteuid,
        .name = "geteuid",
        .num_arguments = 1,
    },
    [SYS_getegid] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getegid,
        .name = "getegid",
        .num_arguments = 1,
    },
    [SYS_setpgid] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_setpgid,
        .name = "setpgid",
        .num_arguments = 2,
    },
    [SYS_getppid] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getppid,
        .name = "getppid",
        .num_arguments = 1,
    },
    [SYS_getpgrp] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getpgrp,
        .name = "getpgrp",
        .num_arguments = 0,
    },
    [SYS_setsid] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_setsid,
        .name = "setsid",
        .num_arguments = 1,
    },
    [SYS_setreuid] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_setreuid,
        .name = "setreuid",
        .num_arguments = 2,
    },
    [SYS_setregid] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_setregid,
        .name = "setregid",
        .num_arguments = 2,
    },
    [SYS_getgroups] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getgroups,
        .name = "getgroups",
        .num_arguments = 2,
    },
    [SYS_setgroups] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_setgroups,
        .name = "setgroups",
        .num_arguments = 2,
    },
    [SYS_setresuid] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_setresuid,
        .name = "setresuid",
        .num_arguments = 3,
    },
    [SYS_getresuid] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getresuid,
        .name = "getresuid",
        .num_arguments = 3,
    },
    [SYS_setresgid] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_setresgid,
        .name = "setresgid",
        .num_arguments = 3,
    },
    [SYS_getresgid] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getresgid,
        .name = "getresgid",
        .num_arguments = 3,
    },
    [SYS_getpgid] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getpgid,
        .name = "getpgid",
        .num_arguments = 1,
    },
    [SYS_setfsuid] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_setfsuid,
        .name = "setfsuid",
        .num_arguments = 1,
    },
    [SYS_setfsgid] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_setfsgid,
        .name = "setfsgid",
        .num_arguments = 1,
    },
    [SYS_getsid] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getsid,
        .name = "getsid",
        .num_arguments = 1,
    },
    [SYS_capget] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_capget,
        .name = "capget",
        .num_arguments = 2,
    },
    [SYS_capset] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_capset,
        .name = "capset",
        .num_arguments = 2,
    },
    [SYS_rt_sigpending] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_rt_sigpending,
        .name = "rt_sigpending",
        .num_arguments = 6,
    },
    [SYS_rt_sigtimedwait] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_rt_sigtimedwait,
        .name = "rt_sigtimedwait",
        .num_arguments = 6,
    },
    [SYS_rt_sigqueueinfo] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_rt_sigqueueinfo,
        .name = "rt_sigqueueinfo",
        .num_arguments = 6,
    },
    [SYS_rt_sigsuspend] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_rt_sigsuspend,
        .name = "rt_sigsuspend",
        .num_arguments = 6,
    },
    [SYS_sigaltstack] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_sigaltstack,
        .name = "sigaltstack",
        .num_arguments = 2,
    },
    [SYS_utime] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_utime,
        .name = "utime",
        .num_arguments = 2,
    },
    [SYS_mknod] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_mknod,
        .name = "mknod",
        .num_arguments = 3,
    },
    [SYS_uselib] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_uselib,
        .name = "uselib",
        .num_arguments = 1,
    },
    [SYS_personality] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_personality,
        .name = "personality",
        .num_arguments = 1,
    },
    [SYS_ustat] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_ustat,
        .name = "ustat",
        .num_arguments = 2,
    },
    [SYS_fstatfs] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_fstatfs,
        .name = "fstatfs",
        .num_arguments = 2,
    },
    [SYS_sysfs] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_sysfs,
        .name = "sysfs",
        .num_arguments = 2,
    },
    [SYS_getpriority] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getpriority,
        .name = "getpriority",
        .num_arguments = 2,
    },
    [SYS_setpriority] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_setpriority,
        .name = "setpriority",
        .num_arguments = 3,
    },
    [SYS_sched_setparam] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_sched_setparam,
        .name = "sched_setparam",
        .num_arguments = 2,
    },
    [SYS_sched_getparam] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_sched_getparam,
        .name = "sched_getparam",
        .num_arguments = 2,
    },
    [SYS_sched_setscheduler] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_sched_setscheduler,
        .name = "sched_setscheduler",
        .num_arguments = 3,
    },
    [SYS_sched_getscheduler] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_sched_getscheduler,
        .name = "sched_getscheduler",
        .num_arguments = 1,
    },
    [SYS_sched_get_priority_max] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_sched_get_priority_max,
        .name = "sched_get_priority_max",
        .num_arguments = 1,
    },
    [SYS_sched_get_priority_min] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_sched_get_priority_min,
        .name = "sched_get_priority_min",
        .num_arguments = 1,
    },
    [SYS_sched_rr_get_interval] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_sched_rr_get_interval,
        .name = "sched_rr_get_interval",
        .num_arguments = 2,
    },
    [SYS_mlock] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_mlock,
        .name = "mlock",
        .num_arguments = 2,
    },
    [SYS_munlock] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_munlock,
        .name = "munlock",
        .num_arguments = 2,
    },
    [SYS_mlockall] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_mlockall,
        .name = "mlockall",
        .num_arguments = 1,
    },
    [SYS_munlockall] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_munlockall,
        .name = "munlockall",
        .num_arguments = 1,
    },
    [SYS_vhangup] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_vhangup,
        .name = "vhangup",
        .num_arguments = 1,
    },
    [SYS_modify_ldt] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_modify_ldt,
        .name = "modify_ldt",
        .num_arguments = 3,
    },
    [SYS_pivot_root] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_pivot_root,
        .name = "pivot_root",
        .num_arguments = 2,
    },
    [SYS__sysctl] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS__sysctl,
        .name = "_sysctl",
        .num_arguments = 1,
    },
    [SYS_prctl] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_prctl,
        .name = "prctl",
        .num_arguments = 5,
    },
    [SYS_adjtimex] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_adjtimex,
        .name = "adjtimex",
        .num_arguments = 1,
    },
    [SYS_setrlimit] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_setrlimit,
        .name = "setrlimit",
        .num_arguments = 2,
    },
    [SYS_chroot] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_chroot,
        .name = "chroot",
        .num_arguments = 1,
    },
    [SYS_sync] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_sync,
        .name = "sync",
        .num_arguments = 1,
    },
    [SYS_acct] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_acct,
        .name = "acct",
        .num_arguments = 1,
    },
    [SYS_settimeofday] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_settimeofday,
        .name = "settimeofday",
        .num_arguments = 2,
    },
    [SYS_mount] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_mount,
        .name = "mount",
        .num_arguments = 5,
    },
    [SYS_umount2] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_umount2,
        .name = "umount2",
        .num_arguments = 2,
    },
    [SYS_swapon] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_swapon,
        .name = "swapon",
        .num_arguments = 2,
    },
    [SYS_swapoff] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_swapoff,
        .name = "swapoff",
        .num_arguments = 1,
    },
    [SYS_reboot] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_reboot,
        .name = "reboot",
        .num_arguments = 4,
    },
    [SYS_sethostname] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_sethostname,
        .name = "sethostname",
        .num_arguments = 2,
    },
    [SYS_setdomainname] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_setdomainname,
        .name = "setdomainname",
        .num_arguments = 2,
    },
    [SYS_iopl] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_iopl,
        .name = "iopl",
        .num_arguments = 1,
    },
    [SYS_ioperm] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_ioperm,
        .name = "ioperm",
        .num_arguments = 3,
    },
    [SYS_create_module] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_create_module,
        .name = "create_module",
        .num_arguments = 2,
    },
    [SYS_init_module] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_init_module,
        .name = "init_module",
        .num_arguments = 3,
    },
    [SYS_delete_module] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_delete_module,
        .name = "delete_module",
        .num_arguments = 2,
    },
    [SYS_get_kernel_syms] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_get_kernel_syms,
        .name = "get_kernel_syms",
        .num_arguments = 1,
    },
    [SYS_query_module] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_query_module,
        .name = "query_module",
        .num_arguments = 5,
    },
    [SYS_quotactl] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_quotactl,
        .name = "quotactl",
        .num_arguments = 4,
    },
    [SYS_nfsservctl] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_nfsservctl,
        .name = "nfsservctl",
        .num_arguments = 3,
    },
    [SYS_getpmsg] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getpmsg,
        .name = "getpmsg",
        .num_arguments = 6,
    },
    [SYS_putpmsg] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_putpmsg,
        .name = "putpmsg",
        .num_arguments = 6,
    },
    [SYS_afs_syscall] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_afs_syscall,
        .name = "afs_syscall",
        .num_arguments = 6,
    },
    [SYS_tuxcall] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_tuxcall,
        .name = "tuxcall",
        .num_arguments = 6,
    },
    [SYS_security] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_security,
        .name = "security",
        .num_arguments = 6,
    },
    [SYS_gettid] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_gettid,
        .name = "gettid",
        .num_arguments = 1,
    },
    [SYS_readahead] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_readahead,
        .name = "readahead",
        .num_arguments = 3,
    },
    [SYS_setxattr] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_setxattr,
        .name = "setxattr",
        .num_arguments = 5,
    },
    [SYS_lsetxattr] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_lsetxattr,
        .name = "lsetxattr",
        .num_arguments = 5,
    },
    [SYS_fsetxattr] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_fsetxattr,
        .name = "fsetxattr",
        .num_arguments = 5,
    },
    [SYS_getxattr] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getxattr,
        .name = "getxattr",
        .num_arguments = 4,
    },
    [SYS_lgetxattr] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_lgetxattr,
        .name = "lgetxattr",
        .num_arguments = 4,
    },
    [SYS_fgetxattr] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_fgetxattr,
        .name = "fgetxattr",
        .num_arguments = 4,
    },
    [SYS_listxattr] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_listxattr,
        .name = "listxattr",
        .num_arguments = 3,
    },
    [SYS_llistxattr] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_llistxattr,
        .name = "llistxattr",
        .num_arguments = 3,
    },
    [SYS_flistxattr] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_flistxattr,
        .name = "flistxattr",
        .num_arguments = 3,
    },
    [SYS_removexattr] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_removexattr,
        .name = "removexattr",
        .num_arguments = 2,
    },
    [SYS_lremovexattr] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_lremovexattr,
        .name = "lremovexattr",
        .num_arguments = 2,
    },
    [SYS_fremovexattr] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_fremovexattr,
        .name = "fremovexattr",
        .num_arguments = 2,
    },
    [SYS_tkill] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_tkill,
        .name = "tkill",
        .num_arguments = 2,
    },
    [SYS_time] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_time,
        .name = "time",
        .num_arguments = 1,
    },
    [SYS_sched_setaffinity] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_sched_setaffinity,
        .name = "sched_setaffinity",
        .num_arguments = 3,
    },
    [SYS_sched_getaffinity] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_sched_getaffinity,
        .name = "sched_getaffinity",
        .num_arguments = 3,
    },
    [SYS_set_thread_area] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_set_thread_area,
        .name = "set_thread_area",
        .num_arguments = 1,
    },
    [SYS_io_setup] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_io_setup,
        .name = "io_setup",
        .num_arguments = 2,
    },
    [SYS_io_destroy] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_io_destroy,
        .name = "io_destroy",
        .num_arguments = 1,
    },
    [SYS_io_getevents] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_io_getevents,
        .name = "io_getevents",
        .num_arguments = 5,
    },
    [SYS_io_submit] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_io_submit,
        .name = "io_submit",
        .num_arguments = 3,
    },
    [SYS_io_cancel] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_io_cancel,
        .name = "io_cancel",
        .num_arguments = 3,
    },
    [SYS_get_thread_area] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_get_thread_area,
        .name = "get_thread_area",
        .num_arguments = 1,
    },
    [SYS_lookup_dcookie] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_lookup_dcookie,
        .name = "lookup_dcookie",
        .num_arguments = 3,
    },
    [SYS_epoll_create] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_epoll_create,
        .name = "epoll_create",
        .num_arguments = 1,
    },
    [SYS_epoll_ctl_old] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_epoll_ctl_old,
        .name = "epoll_ctl_old",
        .num_arguments = 6,
    },
    [SYS_epoll_wait_old] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_epoll_wait_old,
        .name = "epoll_wait_old",
        .num_arguments = 6,
    },
    [SYS_remap_file_pages] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_remap_file_pages,
        .name = "remap_file_pages",
        .num_arguments = 5,
    },
    [SYS_getdents64] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getdents64,
        .name = "getdents64",
        .num_arguments = 3,
    },
    [SYS_restart_syscall] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_restart_syscall,
        .name = "restart_syscall",
        .num_arguments = 1,
    },
    [SYS_semtimedop] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_semtimedop,
        .name = "semtimedop",
        .num_arguments = 4,
    },
    [SYS_fadvise64] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_fadvise64,
        .name = "fadvise64",
        .num_arguments = 6,
    },
    [SYS_timer_create] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_timer_create,
        .name = "timer_create",
        .num_arguments = 3,
    },
    [SYS_timer_settime] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_timer_settime,
        .name = "timer_settime",
        .num_arguments = 4,
    },
    [SYS_timer_gettime] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_timer_gettime,
        .name = "timer_gettime",
        .num_arguments = 2,
    },
    [SYS_timer_getoverrun] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_timer_getoverrun,
        .name = "timer_getoverrun",
        .num_arguments = 1,
    },
    [SYS_timer_delete] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_timer_delete,
        .name = "timer_delete",
        .num_arguments = 1,
    },
    [SYS_clock_settime] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_clock_settime,
        .name = "clock_settime",
        .num_arguments = 2,
    },
    [SYS_clock_gettime] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_clock_gettime,
        .name = "clock_gettime",
        .num_arguments = 2,
    },
    [SYS_clock_getres] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_clock_getres,
        .name = "clock_getres",
        .num_arguments = 2,
    },
    [SYS_clock_nanosleep] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_clock_nanosleep,
        .name = "clock_nanosleep",
        .num_arguments = 4,
    },
    [SYS_epoll_wait] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_epoll_wait,
        .name = "epoll_wait",
        .num_arguments = 4,
    },
    [SYS_epoll_ctl] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_epoll_ctl,
        .name = "epoll_ctl",
        .num_arguments = 4,
    },
    [SYS_tgkill] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_tgkill,
        .name = "tgkill",
        .num_arguments = 3,
    },
    [SYS_utimes] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_utimes,
        .name = "utimes",
        .num_arguments = 2,
    },
    [SYS_vserver] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_vserver,
        .name = "vserver",
        .num_arguments = 6,
    },
    [SYS_mbind] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_mbind,
        .name = "mbind",
        .num_arguments = 6,
    },
    [SYS_set_mempolicy] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_set_mempolicy,
        .name = "set_mempolicy",
        .num_arguments = 3,
    },
    [SYS_get_mempolicy] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_get_mempolicy,
        .name = "get_mempolicy",
        .num_arguments = 5,
    },
    [SYS_mq_open] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_mq_open,
        .name = "mq_open",
        .num_arguments = 2,
    },
    [SYS_mq_unlink] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_mq_unlink,
        .name = "mq_unlink",
        .num_arguments = 1,
    },
    [SYS_mq_timedsend] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_mq_timedsend,
        .name = "mq_timedsend",
        .num_arguments = 5,
    },
    [SYS_mq_timedreceive] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_mq_timedreceive,
        .name = "mq_timedreceive",
        .num_arguments = 5,
    },
    [SYS_mq_notify] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_mq_notify,
        .name = "mq_notify",
        .num_arguments = 2,
    },
    [SYS_mq_getsetattr] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_mq_getsetattr,
        .name = "mq_getsetattr",
        .num_arguments = 3,
    },
    [SYS_kexec_load] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_kexec_load,
        .name = "kexec_load",
        .num_arguments = 4,
    },
    [SYS_waitid] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_waitid,
        .name = "waitid",
        .num_arguments = 4,
    },
    [SYS_add_key] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_add_key,
        .name = "add_key",
        .num_arguments = 5,
    },
    [SYS_request_key] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_request_key,
        .name = "request_key",
        .num_arguments = 4,
    },
    [SYS_keyctl] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_keyctl,
        .name = "keyctl",
        .num_arguments = 2,
    },
    [SYS_ioprio_set] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_ioprio_set,
        .name = "ioprio_set",
        .num_arguments = 3,
    },
    [SYS_ioprio_get] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_ioprio_get,
        .name = "ioprio_get",
        .num_arguments = 2,
    },
    [SYS_inotify_init] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_inotify_init,
        .name = "inotify_init",
        .num_arguments = 1,
    },
    [SYS_inotify_add_watch] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_inotify_add_watch,
        .name = "inotify_add_watch",
        .num_arguments = 3,
    },
    [SYS_inotify_rm_watch] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_inotify_rm_watch,
        .name = "inotify_rm_watch",
        .num_arguments = 2,
    },
    [SYS_migrate_pages] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_migrate_pages,
        .name = "migrate_pages",
        .num_arguments = 4,
    },
    [SYS_mkdirat] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_mkdirat,
        .name = "mkdirat",
        .num_arguments = 3,
    },
    [SYS_mknodat] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_mknodat,
        .name = "mknodat",
        .num_arguments = 4,
    },
    [SYS_fchownat] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_fchownat,
        .name = "fchownat",
        .num_arguments = 5,
    },
    [SYS_futimesat] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_futimesat,
        .name = "futimesat",
        .num_arguments = 3,
    },
    [SYS_unlinkat] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_unlinkat,
        .name = "unlinkat",
        .num_arguments = 3,
    },
    [SYS_renameat] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_renameat,
        .name = "renameat",
        .num_arguments = 4,
    },
    [SYS_linkat] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_linkat,
        .name = "linkat",
        .num_arguments = 5,
    },
    [SYS_symlinkat] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_symlinkat,
        .name = "symlinkat",
        .num_arguments = 3,
    },
    [SYS_readlinkat] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_readlinkat,
        .name = "readlinkat",
        .num_arguments = 4,
    },
    [SYS_fchmodat] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_fchmodat,
        .name = "fchmodat",
        .num_arguments = 4,
    },
    [SYS_faccessat] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_faccessat,
        .name = "faccessat",
        .num_arguments = 4,
    },
    [SYS_pselect6] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_pselect6,
        .name = "pselect6",
        .num_arguments = 6,
    },
    [SYS_ppoll] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_ppoll,
        .name = "ppoll",
        .num_arguments = 4,
    },
    [SYS_unshare] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_unshare,
        .name = "unshare",
        .num_arguments = 1,
    },
    [SYS_get_robust_list] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_get_robust_list,
        .name = "get_robust_list",
        .num_arguments = 3,
    },
    [SYS_splice] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_splice,
        .name = "splice",
        .num_arguments = 6,
    },
    [SYS_tee] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_tee,
        .name = "tee",
        .num_arguments = 4,
    },
    [SYS_sync_file_range] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_sync_file_range,
        .name = "sync_file_range",
        .num_arguments = 4,
    },
    [SYS_vmsplice] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_vmsplice,
        .name = "vmsplice",
        .num_arguments = 4,
    },
    [SYS_move_pages] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_move_pages,
        .name = "move_pages",
        .num_arguments = 6,
    },
    [SYS_utimensat] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_utimensat,
        .name = "utimensat",
        .num_arguments = 4,
    },
    [SYS_epoll_pwait] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_epoll_pwait,
        .name = "epoll_pwait",
        .num_arguments = 5,
    },
    [SYS_signalfd] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_signalfd,
        .name = "signalfd",
        .num_arguments = 3,
    },
    [SYS_timerfd_create] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_timerfd_create,
        .name = "timerfd_create",
        .num_arguments = 2,
    },
    [SYS_eventfd] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_eventfd,
        .name = "eventfd",
        .num_arguments = 2,
    },
    [SYS_fallocate] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_fallocate,
        .name = "fallocate",
        .num_arguments = 4,
    },
    [SYS_timerfd_settime] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_timerfd_settime,
        .name = "timerfd_settime",
        .num_arguments = 4,
    },
    [SYS_timerfd_gettime] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_timerfd_gettime,
        .name = "timerfd_gettime",
        .num_arguments = 2,
    },
    [SYS_accept4] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_accept4,
        .name = "accept4",
        .num_arguments = 4,
    },
    [SYS_signalfd4] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_signalfd4,
        .name = "signalfd4",
        .num_arguments = 6,
    },
    [SYS_eventfd2] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_eventfd2,
        .name = "eventfd2",
        .num_arguments = 6,
    },
    [SYS_epoll_create1] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_epoll_create1,
        .name = "epoll_create1",
        .num_arguments = 1,
    },
    [SYS_dup3] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_dup3,
        .name = "dup3",
        .num_arguments = 3,
    },
    [SYS_pipe2] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_pipe2,
        .name = "pipe2",
        .num_arguments = 2,
    },
    [SYS_inotify_init1] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_inotify_init1,
        .name = "inotify_init1",
        .num_arguments = 1,
    },
    [SYS_preadv] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_preadv,
        .name = "preadv",
        .num_arguments = 4,
    },
    [SYS_pwritev] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_pwritev,
        .name = "pwritev",
        .num_arguments = 4,
    },
    [SYS_rt_tgsigqueueinfo] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_rt_tgsigqueueinfo,
        .name = "rt_tgsigqueueinfo",
        .num_arguments = 6,
    },
    [SYS_perf_event_open] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_perf_event_open,
        .name = "perf_event_open",
        .num_arguments = 5,
    },
    [SYS_recvmmsg] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_recvmmsg,
        .name = "recvmmsg",
        .num_arguments = 5,
    },
    [SYS_fanotify_init] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_fanotify_init,
        .name = "fanotify_init",
        .num_arguments = 2,
    },
    [SYS_fanotify_mark] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_fanotify_mark,
        .name = "fanotify_mark",
        .num_arguments = 5,
    },
    [SYS_name_to_handle_at] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_name_to_handle_at,
        .name = "name_to_handle_at",
        .num_arguments = 5,
    },
    [SYS_open_by_handle_at] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_open_by_handle_at,
        .name = "open_by_handle_at",
        .num_arguments = 3,
    },
    [SYS_clock_adjtime] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_clock_adjtime,
        .name = "clock_adjtime",
        .num_arguments = 6,
    },
    [SYS_syncfs] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_syncfs,
        .name = "syncfs",
        .num_arguments = 1,
    },
    [SYS_sendmmsg] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_sendmmsg,
        .name = "sendmmsg",
        .num_arguments = 4,
    },
    [SYS_setns] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_setns,
        .name = "setns",
        .num_arguments = 2,
    },
    [SYS_getcpu] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_getcpu,
        .name = "getcpu",
        .num_arguments = 3,
    },
    [SYS_process_vm_readv] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_process_vm_readv,
        .name = "process_vm_readv",
        .num_arguments = 6,
    },
    [SYS_process_vm_writev] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_process_vm_writev,
        .name = "process_vm_writev",
        .num_arguments = 6,
    },
    [SYS_kcmp] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_kcmp,
        .name = "kcmp",
        .num_arguments = 5,
    },
    [SYS_finit_module] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_finit_module,
        .name = "finit_module",
        .num_arguments = 3,
    },
    [SYS_sched_setattr] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_sched_setattr,
        .name = "sched_setattr",
        .num_arguments = 3,
    },
    [SYS_sched_getattr] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_sched_getattr,
        .name = "sched_getattr",
        .num_arguments = 4,
    },
    [SYS_renameat2] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_renameat2,
        .name = "renameat2",
        .num_arguments = 5,
    },
    [SYS_seccomp] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_seccomp,
        .name = "seccomp",
        .num_arguments = 3,
    },
    [SYS_memfd_create] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_memfd_create,
        .name = "memfd_create",
        .num_arguments = 2,
    },
    [SYS_kexec_file_load] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_kexec_file_load,
        .name = "kexec_file_load",
        .num_arguments = 5,
    },
    [SYS_bpf] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_bpf,
        .name = "bpf",
        .num_arguments = 3,
    },
    [SYS_userfaultfd] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_userfaultfd,
        .name = "userfaultfd",
        .num_arguments = 6,
    },
    [SYS_membarrier] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_membarrier,
        .name = "membarrier",
        .num_arguments = 2,
    },
    [SYS_mlock2] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_mlock2,
        .name = "mlock2",
        .num_arguments = 3,
    },
    [SYS_copy_file_range] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_copy_file_range,
        .name = "copy_file_range",
        .num_arguments = 6,
    },
    [SYS_preadv2] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_preadv2,
        .name = "preadv2",
        .num_arguments = 5,
    },
    [SYS_pwritev2] = {
        .function = &strace_syscall_print_raw_arguments,
        .number = SYS_pwritev2,
        .name = "pwritev2",
        .num_arguments = 5,
    },
};
static const size_t STRACE_SYSCALL_ENTRIES_COUNT =
    (sizeof(STRACE_SYSCALL_ENTRIES) / sizeof(STRACE_SYSCALL_ENTRIES[0]));
