#!/usr/bin/env python3

import sys
import math
import time

#Print the overload and time
#Function that prints the Overload and the Computation time
def printOverloadAndTime(overload, compTime):
    print("Overload: {:.1f}%".format(overload))
    print("Computation time: {:.2f} ms".format(compTime))

#Print in loop.
#Functions that prints the result in the good format for the output to be the
#exact same as the subject asks.
def printInLoop(k, value):
    if (k + 1) % 5 == 0 or k == 50:
        print(str(k) + " -> " + "{:.3f}".format(value))
    elif (k < 10):
        print(str(k) + " -> " + "{:.3f}".format(value), end="      ")
    else:
        print(str(k) + " -> " + "{:.3f}".format(value), end="     ")

#Calculate Binomial distribution.
#Return the result of a Binomial distribution for a given n, p and k
def calcBinomial(n, k, p):
    ret = math.comb(n, k) * (p ** k) * ((1 - p) ** (n - k))
    return ret

#Binomial Distribution function.
#Main function for the Binomial Distribution. It calculates all the values needed
#for the Binomial Distribution and enters in a loop that calculates and prints the
#value from 0 to 50. It will also calculate the overload and the time it takes
#to do all the calculation.
def hotlineBinomialDistr(p):
    print("Binomial distribution:")
    start = time.time()
    overload = 0
    for k in range(51):
        value = calcBinomial(3500, k, p)
        printInLoop(k, value)
        if k <= 25:
            overload += value
    compTime = time.time() - start
    printOverloadAndTime((1 - overload) * 100, compTime * 1000)

#Calculate Poisson distribution.
#Return the result of a Poisson distribution for a given k and λ
def calcPoisson(k, λ):
    ret = ((λ ** k) / math.factorial(k)) * (math.exp(-λ))
    return ret

#Poisson Distribution function.
#Main function for the Poisson Distribution. It calculates all the values needed
#for the Poisson Distribution and enters in a loop that calculates and prints the
#value from 0 to 50. It will also calculate the overload and the time it takes
#to do all the calculation.
def hotlinePoissonDistr(p):
    print("Poisson distribution:")
    start = time.time()
    λ = 3500 * p
    overload = 0
    for k in range(51):
        value = calcPoisson(k, λ)
        printInLoop(k, value)
        if k <= 25:
            overload += value
    compTime = time.time() - start
    printOverloadAndTime((1 - overload) * 100, compTime * 1000)

#Distributions function.
#Main function for the distributions, it will calculate the probability. A value
#needed by both functions. Then call the Binomial distribution function and the
#Poisson distribution function
def hotlineDistr(av):
    duration = int(av[0])
    if duration < 0:
        raise
    p = duration / (8 * 3600)
    hotlineBinomialDistr(p)
    print()
    hotlinePoissonDistr(p)
    return (0)

#Print combinations.
#Print the result of the combinations to stdout
def printComb(n, k, comb):
    print(str(k) + "-combinations of a set of size " + str(n) + ":\n" + str(comb))

#Combinations function.
#Main function for the combinations, it will call the maths' library function
#"comb" used to calculate combinations and send it to "printComb"
def hotlineComb(av):
    n = int (av[0])
    k = int (av[1])
    if n < 0 or k < 0 or n < k:
        raise
    printComb(n, k, math.comb(n, k))
    return (0)

#Usage function.
#Prints the usage of the program
def usage():
    print("USAGE\n    ./203hotline [n k | d]\n\nDESCRIPTION\n    n      n value for the computation of C(n, k)\n    k      k value for the computation of C(n, k)\n    d      average duration of calls (in seconds)")
    return 0

#Main function.
#It contains a Try Except that prevents any crash of the program and take care
#of error handling in case one of our core function finds a wrong argument
def main(av):
    try:
        ac = len(av)
        if ac == 1 and av[0] == "-h":
            return (usage())
        if ac == 1:
            return (hotlineDistr(av))
        if ac == 2:
            return (hotlineComb(av))
        return 84
    except:
        return 84

#Initialization of main
if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))