/*
** EPITECH PROJECT, 2022
** B-OOP-400-STG-4-1-tekspice-tom.laumonier
** File description:
** test_counter
*/

#include "Counter_4040.hpp"
#include <criterion/criterion.h>

Test(counter, mr_button)
{
    Counter_4040 counter;

    counter.setSinglePin(10, nts::Tristate::TRUE);
    counter.setSinglePin(9, nts::Tristate::TRUE);
    counter.simulate(0);
    cr_expect_eq(counter.compute(8), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(6), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(5), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(4), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(2), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(1), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(3), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(12), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(11), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(13), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(14), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(0), nts::Tristate::FALSE);
}

Test(counter, testing_each_output)
{
    Counter_4040 counter;

    counter.setSinglePin(10, nts::Tristate::FALSE);
    counter.setSinglePin(9, nts::Tristate::FALSE);
    counter.simulate(1);
    cr_expect_eq(counter.compute(8), nts::Tristate::TRUE);
    cr_expect_eq(counter.compute(6), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(5), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(4), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(2), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(1), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(3), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(12), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(11), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(13), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(14), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(0), nts::Tristate::FALSE);
    counter.simulate(2);
    cr_expect_eq(counter.compute(8), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(6), nts::Tristate::TRUE);
    cr_expect_eq(counter.compute(5), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(4), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(2), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(1), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(3), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(12), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(11), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(13), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(14), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(0), nts::Tristate::FALSE);
    counter.simulate(4);
    cr_expect_eq(counter.compute(8), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(6), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(5), nts::Tristate::TRUE);
    cr_expect_eq(counter.compute(4), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(2), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(1), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(3), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(12), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(11), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(13), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(14), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(0), nts::Tristate::FALSE);
    counter.simulate(8);
    cr_expect_eq(counter.compute(8), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(6), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(5), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(4), nts::Tristate::TRUE);
    cr_expect_eq(counter.compute(2), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(1), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(3), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(12), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(11), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(13), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(14), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(0), nts::Tristate::FALSE);
    counter.simulate(16);
    cr_expect_eq(counter.compute(8), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(6), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(5), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(4), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(2), nts::Tristate::TRUE);
    cr_expect_eq(counter.compute(1), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(3), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(12), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(11), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(13), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(14), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(0), nts::Tristate::FALSE);
    counter.simulate(32);
    cr_expect_eq(counter.compute(8), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(6), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(5), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(4), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(2), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(1), nts::Tristate::TRUE);
    cr_expect_eq(counter.compute(3), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(12), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(11), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(13), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(14), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(0), nts::Tristate::FALSE);
    counter.simulate(64);
    cr_expect_eq(counter.compute(8), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(6), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(5), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(4), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(2), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(1), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(3), nts::Tristate::TRUE);
    cr_expect_eq(counter.compute(12), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(11), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(13), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(14), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(0), nts::Tristate::FALSE);
    counter.simulate(128);
    cr_expect_eq(counter.compute(8), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(6), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(5), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(4), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(2), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(1), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(3), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(12), nts::Tristate::TRUE);
    cr_expect_eq(counter.compute(11), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(13), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(14), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(0), nts::Tristate::FALSE);
    counter.simulate(256);
    cr_expect_eq(counter.compute(8), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(6), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(5), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(4), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(2), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(1), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(3), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(12), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(11), nts::Tristate::TRUE);
    cr_expect_eq(counter.compute(13), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(14), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(0), nts::Tristate::FALSE);
    counter.simulate(512);
    cr_expect_eq(counter.compute(8), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(6), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(5), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(4), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(2), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(1), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(3), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(12), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(11), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(13), nts::Tristate::TRUE);
    cr_expect_eq(counter.compute(14), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(0), nts::Tristate::FALSE);
    counter.simulate(1024);
    cr_expect_eq(counter.compute(8), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(6), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(5), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(4), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(2), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(1), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(3), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(12), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(11), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(13), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(14), nts::Tristate::TRUE);
    cr_expect_eq(counter.compute(0), nts::Tristate::FALSE);
    counter.simulate(2048);
    cr_expect_eq(counter.compute(8), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(6), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(5), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(4), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(2), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(1), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(3), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(12), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(11), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(13), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(14), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(0), nts::Tristate::TRUE);
    counter.simulate(4095);
    cr_expect_eq(counter.compute(8), nts::Tristate::TRUE);
    cr_expect_eq(counter.compute(6), nts::Tristate::TRUE);
    cr_expect_eq(counter.compute(5), nts::Tristate::TRUE);
    cr_expect_eq(counter.compute(4), nts::Tristate::TRUE);
    cr_expect_eq(counter.compute(2), nts::Tristate::TRUE);
    cr_expect_eq(counter.compute(1), nts::Tristate::TRUE);
    cr_expect_eq(counter.compute(3), nts::Tristate::TRUE);
    cr_expect_eq(counter.compute(12), nts::Tristate::TRUE);
    cr_expect_eq(counter.compute(11), nts::Tristate::TRUE);
    cr_expect_eq(counter.compute(13), nts::Tristate::TRUE);
    cr_expect_eq(counter.compute(14), nts::Tristate::TRUE);
    cr_expect_eq(counter.compute(0), nts::Tristate::TRUE);
    counter.simulate(4096);
    cr_expect_eq(counter.compute(8), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(6), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(5), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(4), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(2), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(1), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(3), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(12), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(11), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(13), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(14), nts::Tristate::FALSE);
    cr_expect_eq(counter.compute(0), nts::Tristate::FALSE);
}