/*
** EPITECH PROJECT, 2022
** B-NWP-400-STG-4-1-myteams-jeffrey.winkler
** File description:
** cmd_ids
*/

#pragma once

#define RESPONSE_ID 0

#define LOGIN_ID 1
#define LOGOUT_ID 2
#define CREATE_TEAM_ID 3
#define CREATE_CHANNEL_ID 4
#define CREATE_THREAD_ID 5
#define CREATE_COMMENT_ID 6
#define SEND_PM_ID 7
#define GET_PMS_ID 8
#define SUBSCRIBE_ID 9
#define UNSUBSCRIBE_ID 10
#define LIST_USERS_ID 11
#define LIST_TEAMS_ID 12
#define LIST_CHANNELS_ID 13
#define LIST_THREADS_ID 14
#define LIST_COMMENTS_ID 15
#define LIST_SUBSCRIBED_TEAMS_ID 16
#define LIST_USERS_SUBSCRIBED_TO_TEAM_ID 17
#define INFO_USER_ID 18
#define INFO_CURRENT_USER_ID 19
#define INFO_TEAM_ID 20
#define INFO_CHANNEL_ID 21
#define INFO_THREAD_ID 22

#define EVENT_USER_LOGIN_ID 23
#define EVENT_USER_LOGOUT_ID 24
#define EVENT_TEAM_CREATED 25
#define EVENT_PM_RECEIVED_ID 26
#define EVENT_TEAM_CREATED_ID 27
#define EVENT_CHANNEL_CREATED_ID 28
#define EVENT_THREAD_CREATED_ID 29
#define EVENT_REPLY_CREATED_ID 30

#define NULL_COMMAND_ID 255
