- name: copy the .tar
  become: yes
  copy:
    src: poll.tar
    dest: /root/poll.tar

- name: unzip the .tar
  become: yes
  unarchive:
    src: /root/poll.tar
    dest: /root
    remote_src: yes
  register: is_require_needed

- name: install dependencies
  become: yes
  pip:
    requirements: /root/poll/requirements.txt
    executable: pip3
    state: forcereinstall
  when: not is_require_needed

- name: copy service
  become: yes
  copy:
    src: roles/poll/files/poll.service
    dest: /etc/systemd/system/poll.service
